import type { Metadata } from "next";
import localFont from "next/font/local";
import Safari from "../components/magicui/Safari";
import "./globals.css";
import Meteors from "../components/magicui/Meteors";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative bg-blue-600 bg-texture min-h-screen flex items-center justify-center`}
      >
        <div className="relative">
            <div className="flex flex-col justify-center h-full px-[35px]">
              {children}
            </div>
        </div>

      </body>
    </html>
  );
}
